import test from "node:test";import assert from "node:assert/strict";
function calculate(accounts,txs,period){const start=period.length===7?`${period}-01`:`${period}-01-01`,end=period.length===7?`${period}-31`:`${period}-12-31`,opening=new Map(accounts.map(a=>[a.id,a.opening||0])),debit=new Map,credit=new Map;for(const t of txs){if(t.date<start)for(const e of t.entries)opening.set(e.id,(opening.get(e.id)||0)+e.amount);else if(t.date<=end)for(const e of t.entries)e.amount<0?debit.set(e.id,(debit.get(e.id)||0)-e.amount):credit.set(e.id,(credit.get(e.id)||0)+e.amount)}return accounts.map(a=>({id:a.id,opening:opening.get(a.id)||0,debit:debit.get(a.id)||0,credit:credit.get(a.id)||0,closing:(opening.get(a.id)||0)-(debit.get(a.id)||0)+(credit.get(a.id)||0)}))}
const accounts=[{id:1,type:'income'},{id:2,type:'expense'},{id:3,type:'bank'},{id:4,type:'capital'}],txs=[{date:'2025-06-01',entries:[{id:1,amount:100},{id:3,amount:-100}]},{date:'2026-02-01',entries:[{id:1,amount:50},{id:3,amount:-50}]},{date:'2026-03-01',entries:[{id:2,amount:-20},{id:3,amount:20}]}];
test('every voucher is balanced',()=>{for(const t of txs)assert.equal(t.entries.reduce((s,e)=>s+e.amount,0),0)});
test('income statement contains only selected-period activity',()=>{const r=calculate(accounts,txs,'2026'),income=r.find(x=>x.id===1),expense=r.find(x=>x.id===2);assert.equal(income.opening,100);assert.equal(income.credit-income.debit,50);assert.equal(expense.debit-expense.credit,20);assert.equal((income.credit-income.debit)-(expense.debit-expense.credit),30)});
test('balance sheet closing includes opening plus period activity',()=>{const r=calculate(accounts,txs,'2026'),bank=r.find(x=>x.id===3);assert.equal(bank.opening,-100);assert.equal(bank.closing,-130)});
test('month period excludes other months but carries their balance',()=>{const r=calculate(accounts,txs,'2026-03'),income=r.find(x=>x.id===1),expense=r.find(x=>x.id===2);assert.equal(income.opening,150);assert.equal(income.credit,0);assert.equal(expense.debit,20)});
test('Tally Balance Sheet groups never enter nominal reports',()=>{const nominal=p=>/^(direct incomes|indirect incomes|sales accounts|direct expenses|indirect expenses|purchase accounts)$/.test(p.toLowerCase());for(const group of ['Fixed Assets','Current Assets','Investments','Capital Account','Current Liabilities','Loans (Liability)'])assert.equal(nominal(group),false)});

test('Credit cards follow the authoritative Bank Accounts parent',()=>{const parent='Bank Accounts'.toLowerCase();const isBank=/^(bank accounts|cash-in-hand)$/.test(parent);const isLiability=/^(capital account|current liabilities|loans \\(liability\\))$/.test(parent);assert.equal(isBank,true);assert.equal(isLiability,false)});

test('capital receives only the selected period result',()=>{const r=calculate(accounts,txs,'2026'),income=r.find(x=>x.id===1),expense=r.find(x=>x.id===2);const current=(income.credit-income.debit)-(expense.debit-expense.credit);assert.equal(current,30);assert.notEqual(current,130)});

test('custom April to June range carries opening and includes only range activity',()=>{const rangeTxs=[{date:'2026-03-31',entries:[{id:3,amount:-10}]},{date:'2026-04-01',entries:[{id:3,amount:-20}]},{date:'2026-06-30',entries:[{id:3,amount:-30}]},{date:'2026-07-01',entries:[{id:3,amount:-40}]}];const start='2026-04-01',end='2026-06-31';let opening=0,activity=0,count=0;for(const tx of rangeTxs){if(tx.date<start)opening+=tx.entries[0].amount;else if(tx.date<=end){activity+=tx.entries[0].amount;count++}}assert.equal(opening,-10);assert.equal(activity,-50);assert.equal(count,2);assert.equal(opening+activity,-60)})

test('fiscal year 2026 runs April 2026 through March 2027',()=>{const dates=['2026-03-31','2026-04-01','2027-03-31','2027-04-01'];const start='2026-04-01',end='2027-03-31';assert.deepEqual(dates.filter(d=>d>=start&&d<=end),['2026-04-01','2027-03-31'])})
