import test from "node:test";import assert from "node:assert/strict";
function calculate(accounts,txs,period){const start=period.length===7?`${period}-01`:`${period}-01-01`,end=period.length===7?`${period}-31`:`${period}-12-31`,opening=new Map(accounts.map(a=>[a.id,a.opening||0])),debit=new Map,credit=new Map;for(const t of txs){if(t.date<start)for(const e of t.entries)opening.set(e.id,(opening.get(e.id)||0)+e.amount);else if(t.date<=end)for(const e of t.entries)e.amount<0?debit.set(e.id,(debit.get(e.id)||0)-e.amount):credit.set(e.id,(credit.get(e.id)||0)+e.amount)}return accounts.map(a=>({id:a.id,opening:opening.get(a.id)||0,debit:debit.get(a.id)||0,credit:credit.get(a.id)||0,closing:(opening.get(a.id)||0)-(debit.get(a.id)||0)+(credit.get(a.id)||0)}))}
const accounts=[{id:1,type:'income'},{id:2,type:'expense'},{id:3,type:'bank'},{id:4,type:'capital'}],txs=[{date:'2025-06-01',entries:[{id:1,amount:100},{id:3,amount:-100}]},{date:'2026-02-01',entries:[{id:1,amount:50},{id:3,amount:-50}]},{date:'2026-03-01',entries:[{id:2,amount:-20},{id:3,amount:20}]}];
test('every voucher is balanced',()=>{for(const t of txs)assert.equal(t.entries.reduce((s,e)=>s+e.amount,0),0)});
test('income statement contains only selected-period activity',()=>{const r=calculate(accounts,txs,'2026'),income=r.find(x=>x.id===1),expense=r.find(x=>x.id===2);assert.equal(income.opening,100);assert.equal(income.credit-income.debit,50);assert.equal(expense.debit-expense.credit,20);assert.equal((income.credit-income.debit)-(expense.debit-expense.credit),30)});
test('balance sheet closing includes opening plus period activity',()=>{const r=calculate(accounts,txs,'2026'),bank=r.find(x=>x.id===3);assert.equal(bank.opening,-100);assert.equal(bank.closing,-130)});
test('month period excludes other months but carries their balance',()=>{const r=calculate(accounts,txs,'2026-03'),income=r.find(x=>x.id===1),expense=r.find(x=>x.id===2);assert.equal(income.opening,150);assert.equal(income.credit,0);assert.equal(expense.debit,20)});
test('Tally Balance Sheet groups never enter nominal reports',()=>{const nominal=p=>/^(direct incomes|indirect incomes|sales accounts|direct expenses|indirect expenses|purchase accounts)$/.test(p.toLowerCase());for(const group of ['Fixed Assets','Current Assets','Investments','Capital Account','Current Liabilities','Loans (Liability)'])assert.equal(nominal(group),false)});

test('Credit cards follow the authoritative Bank Accounts parent',()=>{const parent='Bank Accounts'.toLowerCase();const isBank=/^(bank accounts|cash-in-hand)$/.test(parent);const isLiability=/^(capital account|current liabilities|loans \\(liability\\))$/.test(parent);assert.equal(isBank,true);assert.equal(isLiability,false)});

test('capital receives only the selected period result',()=>{const r=calculate(accounts,txs,'2026'),income=r.find(x=>x.id===1),expense=r.find(x=>x.id===2);const current=(income.credit-income.debit)-(expense.debit-expense.credit);assert.equal(current,30);assert.notEqual(current,130)});

test('custom April to June range carries opening and includes only range activity',()=>{const rangeTxs=[{date:'2026-03-31',entries:[{id:3,amount:-10}]},{date:'2026-04-01',entries:[{id:3,amount:-20}]},{date:'2026-06-30',entries:[{id:3,amount:-30}]},{date:'2026-07-01',entries:[{id:3,amount:-40}]}];const start='2026-04-01',end='2026-06-31';let opening=0,activity=0,count=0;for(const tx of rangeTxs){if(tx.date<start)opening+=tx.entries[0].amount;else if(tx.date<=end){activity+=tx.entries[0].amount;count++}}assert.equal(opening,-10);assert.equal(activity,-50);assert.equal(count,2);assert.equal(opening+activity,-60)})

test('fiscal year 2026 runs April 2026 through March 2027',()=>{const dates=['2026-03-31','2026-04-01','2027-03-31','2027-04-01'];const start='2026-04-01',end='2027-03-31';assert.deepEqual(dates.filter(d=>d>=start&&d<=end),['2026-04-01','2027-03-31'])})

test('table filtering and sorting do not alter report totals',()=>{const rows=[{name:'Bank',closing:-100},{name:'Cash',closing:-50},{name:'Income',closing:150}],total=rows.reduce((s,r)=>s+r.closing,0),view=rows.filter(r=>/bank|cash/i.test(r.name)).sort((a,b)=>Math.abs(b.closing)-Math.abs(a.closing));assert.deepEqual(view.map(r=>r.name),['Bank','Cash']);assert.equal(rows.reduce((s,r)=>s+r.closing,0),total)})

test('copied voucher receives a new identity and leaves original unchanged',()=>{const original={guid:'old',date:'2026-07-09',number:'249',entries:[{id:1,amount:-1.97},{id:2,amount:1.97}]},copy={...structuredClone(original),guid:'new',date:'2026-07-10',entries:[{id:1,amount:-2.5},{id:2,amount:2.5}]};assert.equal(original.date,'2026-07-09');assert.equal(original.entries[0].amount,-1.97);assert.notEqual(copy.guid,original.guid);assert.equal(copy.entries.reduce((s,e)=>s+e.amount,0),0)})

test('editing replaces one voucher while preserving identity and balance',()=>{const original={id:7,guid:'same',date:'2026-07-09',entries:[{id:1,amount:-2},{id:2,amount:2}]},other={id:8,guid:'other',date:'2026-07-10',entries:[]},edited={...original,date:'2026-07-11',entries:[{id:3,amount:-5},{id:4,amount:5}]},result=[original,other].map(t=>t.guid===edited.guid?edited:t);assert.equal(result.length,2);assert.equal(result[0].id,7);assert.equal(result[0].guid,'same');assert.equal(result[0].date,'2026-07-11');assert.equal(result[0].entries.reduce((s,e)=>s+e.amount,0),0)})

test('voucher numbers run independently by type and April-March fiscal year',()=>{const txs=[{type:'Payment',date:'2026-04-01',number:'249'},{type:'Receipt',date:'2026-04-02',number:'37'},{type:'Payment',date:'2027-03-31',number:'250'},{type:'Payment',date:'2027-04-01',number:'1'}],fy=d=>Number(d.slice(5,7))>=4?Number(d.slice(0,4)):Number(d.slice(0,4))-1,next=(type,date)=>Math.max(0,...txs.filter(t=>t.type===type&&fy(t.date)===fy(date)).map(t=>Number(t.number)))+1;assert.equal(next('Payment','2026-07-10'),251);assert.equal(next('Receipt','2026-07-10'),38);assert.equal(next('Payment','2027-04-02'),2)})
test('new local duplicate is renumbered after historical voucher',()=>{const txs=[{historical:true,type:'Payment',number:'249'},{historical:false,type:'Payment',number:'249'}],seen=new Set;let max=0;for(const t of txs.sort((a,b)=>Number(b.historical)-Number(a.historical))){max=Math.max(max,Number(t.number));if(!t.historical&&seen.has(t.number))t.number=String(++max);seen.add(t.number)}assert.deepEqual(txs.map(t=>t.number),['249','250'])})

test('dashboard salary card uses the full current April-March fiscal year',()=>{const salary=[{date:'2026-03-31',amount:100},{date:'2026-04-01',amount:200},{date:'2027-03-31',amount:300},{date:'2027-04-01',amount:400}],total=salary.filter(x=>x.date>='2026-04-01'&&x.date<='2027-03-31').reduce((s,x)=>s+x.amount,0);assert.equal(total,500)})
test('dashboard detail rows reconcile to their card total',()=>{const rows=[{closing:100},{closing:-25},{closing:50}],card=rows.reduce((s,r)=>s+r.closing,0);assert.equal(card,125)})

test('investment dashboard follows Tally parent group and excludes income ledgers',()=>{const ledgers=[{name:'401K Investments',parent:'Investments',category:'Investment'},{name:'Sale of Share',parent:'Indirect Incomes',category:'Investment'},{name:'Sale of Shares - Gain / Loss',parent:'Indirect Incomes',category:'Investment'}],investment=ledgers.filter(a=>/^investments$/i.test(a.parent));assert.deepEqual(investment.map(a=>a.name),['401K Investments'])})

test('balance sheet transfers only current fiscal-year result, not accumulated history',()=>{const nominal=[{date:'2025-04-01',amount:1000},{date:'2026-03-31',amount:-200},{date:'2026-04-01',amount:300},{date:'2026-07-10',amount:-50}],closing='2026-07-10',fyStart='2026-04-01',current=nominal.filter(x=>x.date>=fyStart&&x.date<=closing).reduce((s,x)=>s+x.amount,0),accumulated=nominal.reduce((s,x)=>s+x.amount,0);assert.equal(current,250);assert.equal(accumulated,1050);assert.notEqual(current,accumulated)})
test('balance sheet current-year result plus carried capital avoids double counting',()=>{const carriedCapital=800,currentYearResult=250;assert.equal(carriedCapital+currentYearResult,1050)})

test('closing-balance reports suppress positive and negative zero rows',()=>{const tol=.005,rows=[{name:'Zero',closing:0},{name:'Negative zero',closing:-0},{name:'Rounded zero',closing:.004},{name:'Bank',closing:10}];assert.deepEqual(rows.filter(r=>Math.abs(r.closing)>tol).map(r=>r.name),['Bank'])})
test('dashboard capital adds the applicable income statement result',()=>{const capital=1057378.02,currentFY=-43466.54,selectedPeriod=-1000;assert.equal(capital+currentFY,1013911.48);assert.equal(capital+selectedPeriod,1056378.02)})

test('mobile and desktop synchronization retain the same voucher identity',()=>{const cloud={guid:'shared-voucher',number:'251',amount:10},phone=structuredClone(cloud),desktop=structuredClone(cloud);assert.deepEqual(phone,desktop)})
test('service worker must not cache encrypted vault API responses',()=>{const apiPath='/api/vault',shouldHandle=!apiPath.startsWith('/api/');assert.equal(shouldHandle,false)})

test('biometric enrollment stores only encrypted local material',()=>{const stored={credentialId:'public-id',salt:'public-salt',iv:'public-iv',sealed:'ciphertext'};assert.equal('password' in stored,false);assert.equal('biometric' in stored,false);assert.equal(typeof stored.sealed,'string')})
test('biometric configuration is device-local and never part of cloud vault',()=>{const cloudKeys=['version','iterations','salt','iv','tag','ciphertext'];assert.equal(cloudKeys.includes('credentialId'),false);assert.equal(cloudKeys.includes('sealedPassword'),false)})
