const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto'),zlib=require('zlib');
const book=String(process.argv[2]||'').toLowerCase();if(!['us','india'].includes(book))throw Error('Book must be us or india');const tallyPort=book==='us'?9001:9000;
const site='https://personal-ledger-dk.digneshkhatri.workers.dev',B=s=>Buffer.from(s,'base64'),b64=b=>Buffer.from(b).toString('base64'),norm=s=>String(s||'').trim().toLowerCase(),esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
function key(v,p){return crypto.pbkdf2Sync(p,B(v.salt),v.iterations,32,'sha256')}function decrypt(v,p){const d=crypto.createDecipheriv('aes-256-gcm',key(v,p),B(v.iv));d.setAuthTag(B(v.tag));return JSON.parse(zlib.gunzipSync(Buffer.concat([d.update(B(v.ciphertext)),d.final()])).toString('utf8'))}
function encrypt(data,p){const iv=crypto.randomBytes(12),salt=crypto.randomBytes(16),iterations=600000,k=crypto.pbkdf2Sync(p,salt,iterations,32,'sha256'),c=crypto.createCipheriv('aes-256-gcm',k,iv),plain=zlib.gzipSync(Buffer.from(JSON.stringify(data))),cipher=Buffer.concat([c.update(plain),c.final()]);return{version:1,algorithm:'AES-256-GCM',kdf:'PBKDF2-SHA256',iterations,salt:b64(salt),iv:b64(iv),tag:b64(c.getAuthTag()),ciphertext:b64(cipher)}}
function decode(s){return String(s||'').replace(/&amp;/g,'&').replace(/&apos;/g,"'").replace(/&quot;/g,'"').trim()}function tag(body,name){const m=body.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'));return decode(m?.[1]||'')}function attr(raw,name){return decode(raw.match(new RegExp(`${name}="([^"]*)"`,'i'))?.[1]||'')}
function post(xml){return new Promise((resolve,reject)=>{const q=http.request({host:'127.0.0.1',port:tallyPort,method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8','Content-Length':Buffer.byteLength(xml)}},r=>{const a=[];r.on('data',x=>a.push(x));r.on('end',()=>resolve(Buffer.concat(a).toString('utf8')))});q.setTimeout(90000,()=>q.destroy(Error('Tally master request timed out')));q.on('error',reject);q.end(xml)})}
function exportXml(type){const id=`PL ${type} Masters`;return`<ENVELOPE><HEADER><VERSION>1</VERSION><TALLYREQUEST>Export</TALLYREQUEST><TYPE>Collection</TYPE><ID>${id}</ID></HEADER><BODY><DESC><STATICVARIABLES><SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT></STATICVARIABLES><TDL><TDLMESSAGE><COLLECTION NAME="${id}" ISMODIFY="No"><TYPE>${type}</TYPE><FETCH>GUID,MasterID,Name,Parent,OpeningBalance,CurrencyName</FETCH></COLLECTION></TDLMESSAGE></TDL></DESC></BODY></ENVELOPE>`}
function ledgerBalanceXml(){const id='PL Ledger Balances';return`<ENVELOPE><HEADER><VERSION>1</VERSION><TALLYREQUEST>Export</TALLYREQUEST><TYPE>Collection</TYPE><ID>${id}</ID></HEADER><BODY><DESC><STATICVARIABLES><SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT></STATICVARIABLES><TDL><TDLMESSAGE><COLLECTION NAME="${id}" ISMODIFY="No"><TYPE>Ledger</TYPE><FETCH>Name,Parent,ClosingBalance</FETCH></COLLECTION></TDLMESSAGE></TDL></DESC></BODY></ENVELOPE>`}
function parseLedgerBalances(xml){const out=[];for(const m of xml.matchAll(/<LEDGER([^>]*)>([\s\S]*?)<\/LEDGER>/gi)){const raw=m[1],body=m[2],name=tag(body,'NAME')||attr(raw,'NAME');if(!name)continue;out.push({name,parent:tag(body,'PARENT'),closingBalance:Number(tag(body,'CLOSINGBALANCE').replace(/,/g,'')||0)})}return out}
function parse(xml,type){const out=[];for(const m of xml.matchAll(new RegExp(`<${type}([^>]*)>([\\s\\S]*?)<\\/${type}>`,'gi'))){const raw=m[1],body=m[2],name=tag(body,'NAME')||attr(raw,'NAME');if(!name)continue;out.push({guid:tag(body,'GUID'),masterId:Number(tag(body,'MASTERID')||0),name,parent:tag(body,'PARENT'),openingBalance:Number(tag(body,'OPENINGBALANCE').replace(/,/g,'')||0),currency:tag(body,'CURRENCYNAME')})}return out}
const ledgerFp=x=>JSON.stringify([norm(x.name),norm(x.parent),Math.round(Number(x.openingBalance||0)*100),norm(x.currency)]),groupFp=x=>JSON.stringify([norm(x.name),norm(x.parent)]);
function nature(name){const n=norm(name);if(/(asset)/.test(n))return'Asset';if(/income|sales/.test(n))return'Income';if(/expense|purchase/.test(n))return'Expense';if(/capital|reserve/.test(n))return'Capital';if(/liabilit|creditor|provision|duties|loan/.test(n))return'Liability';if(/bank account/.test(n))return'Bank';if(/cash/.test(n))return'Cash';if(/investment/.test(n))return'Investment';return'Asset'}
async function load(auth,pw){const url=site+'/api/vault'+(book==='india'?'?book=india':'');const r=await fetch(url,{headers:{Authorization:auth}});if(!r.ok)throw Error('Cloud HTTP '+r.status);const raw=await r.text();return{url,raw,etag:'"'+crypto.createHash('sha256').update(raw).digest('hex')+'"',vault:decrypt(JSON.parse(raw),pw)}}
async function put(state,pw,message){const backup=path.join(__dirname,`encrypted-${book}-vault-before-master-${new Date().toISOString().replace(/[:.]/g,'-')}.json`);fs.writeFileSync(backup,state.raw);const body=JSON.stringify(encrypt(state.vault,pw)),accessToken=process.env.PL_ACCESS_CODE||'';if(!accessToken)throw Error('PL_ACCESS_CODE not set -- required for /api/vault writes');const r=await fetch(state.url,{method:'PUT',headers:{Authorization:state.auth,'Content-Type':'application/json','If-Match':state.etag,'x-dk-access-token':accessToken},body});if(!r.ok)throw Error('Master cloud update failed HTTP '+r.status);console.log(message);console.log('Master backup: '+backup)}
function importXml(kind,item,action,original){const type=kind==='group'?'GROUP':'LEDGER',name=original||item.name,extra=kind==='group'?`<NAME>${esc(item.name)}</NAME><PARENT>${esc(item.parent||'')}</PARENT>`:`<NAME>${esc(item.name)}</NAME><PARENT>${esc(item.parent)}</PARENT><OPENINGBALANCE>${Number(item.openingBalance||0).toFixed(2)}</OPENINGBALANCE>`;return`<ENVELOPE><HEADER><VERSION>1</VERSION><TALLYREQUEST>Import</TALLYREQUEST><TYPE>Data</TYPE><ID>All Masters</ID></HEADER><BODY><DESC></DESC><DATA><TALLYMESSAGE xmlns:UDF="TallyUDF"><${type} NAME="${esc(name)}" ACTION="${action}">${extra}</${type}></TALLYMESSAGE></DATA></BODY></ENVELOPE>`}
(async()=>{try{const sp=process.env.PL_SITE_PASSWORD||'',pw=process.env.PL_VAULT_PASSWORD||'';if(!sp||!pw)throw Error('Master-sync credentials missing');const auth='Basic '+Buffer.from('master-sync:'+sp).toString('base64'),state=await load(auth,pw);state.auth=auth;const tallyGroups=parse(await post(exportXml('GROUP')),'GROUP'),tallyLedgers=parse(await post(exportXml('LEDGER')),'LEDGER'),groups=state.vault.groups||(state.vault.groups=[]),accounts=state.vault.accounts||[],groupByName=new Map(tallyGroups.map(x=>[norm(x.name),x])),ledgerByName=new Map(tallyLedgers.map(x=>[norm(x.name),x]));let linked=0;
for(const a of accounts)if(!a.masterFingerprint){const t=tallyLedgers.find(t=>(a.tallyGuid&&t.guid&&norm(t.guid)===norm(a.tallyGuid))||(a.tallyMasterId&&Number(t.masterId)===Number(a.tallyMasterId)))||ledgerByName.get(norm(a.name));if(t){a.tallyGuid=t.guid||a.tallyGuid;a.tallyMasterId=t.masterId||a.tallyMasterId;a.name=t.name||a.name;a.parent=t.parent||a.parent;a.category=nature(t.parent||a.parent||a.category);a.currency=t.currency||a.currency;a.openingBalance=t.openingBalance;a.masterOriginalName=t.name||a.name;a.masterFingerprint=ledgerFp(t);a.masterSyncStatus='synced';linked++}}
for(const t of tallyGroups){let g=groups.find(x=>norm(x.name)===norm(t.name));if(!g){g={name:t.name,parent:t.parent||undefined,nature:nature(t.name),active:true};groups.push(g)}if(!g.masterFingerprint){g.tallyGuid=t.guid||g.tallyGuid;g.tallyMasterId=t.masterId||g.tallyMasterId;g.masterOriginalName=g.name;g.masterFingerprint=groupFp(t);g.masterSyncStatus='synced';linked++}}
if(linked){await put(state,pw,`MASTER_BASELINE_INITIALIZED: ${linked} identity link(s)`);return}
const pendingGroup=groups.find(g=>g.masterSyncStatus==='pending'),pendingAccount=accounts.find(a=>a.masterSyncStatus==='pending'||(!a.masterFingerprint&&!a.tallyGuid&&!a.tallyMasterId&&!ledgerByName.has(norm(a.name)))),pending=pendingGroup?{kind:'group',item:pendingGroup}:pendingAccount?{kind:'ledger',item:pendingAccount}:null;if(pending)console.log('MASTER_PENDING_DETECTED: '+pending.kind+' '+pending.item.name);
if(pending?.item.masterDeletePending){const source=pending.kind==='group'?tallyGroups:tallyLedgers,t=source.find(x=>(pending.item.tallyGuid&&x.guid===pending.item.tallyGuid)||norm(x.name)===norm(pending.item.masterOriginalName||pending.item.name));if(!t){if(pending.kind==='group')state.vault.groups=groups.filter(g=>g!==pending.item);else state.vault.accounts=accounts.filter(a=>a!==pending.item);await put(state,pw,`MASTER_ACTION_APPLIED: ${pending.kind} delete finalized ${pending.item.name}`);return}const response=await post(importXml(pending.kind,pending.item,'Delete',t.name));if(!/<ERRORS>0<\/ERRORS>/.test(response)||String((response.match(/<LINEERROR>([\s\S]*?)<\/LINEERROR>/i)||[])[1]||'').trim())throw Error('Tally rejected master delete: '+String((response.match(/<LINEERROR>([\s\S]*?)<\/LINEERROR>/i)||[])[1]||'unknown error').trim());const after=pending.kind==='group'?parse(await post(exportXml('GROUP')),'GROUP'):parse(await post(exportXml('LEDGER')),'LEDGER');if(after.some(x=>norm(x.name)===norm(t.name)))throw Error('Master delete post-write verification failed');if(pending.kind==='group')state.vault.groups=groups.filter(g=>g!==pending.item);else state.vault.accounts=accounts.filter(a=>a!==pending.item);await put(state,pw,`MASTER_ACTION_APPLIED: ${pending.kind} deleted ${pending.item.name}`);return}
if(pending){const t=pending.kind==='group'?tallyGroups.find(x=>x.guid&&x.guid===pending.item.tallyGuid)||groupByName.get(norm(pending.item.masterOriginalName)):tallyLedgers.find(x=>x.guid&&x.guid===pending.item.tallyGuid)||ledgerByName.get(norm(pending.item.masterOriginalName)),action=t?'Alter':'Create',response=await post(importXml(pending.kind,pending.item,action,t?.name));if(!/<ERRORS>0<\/ERRORS>/.test(response)||String((response.match(/<LINEERROR>([\s\S]*?)<\/LINEERROR>/i)||[])[1]||'').trim())throw Error('Tally rejected master write: '+String((response.match(/<LINEERROR>([\s\S]*?)<\/LINEERROR>/i)||[])[1]||'unknown error').trim());const after=pending.kind==='group'?parse(await post(exportXml('GROUP')),'GROUP'):parse(await post(exportXml('LEDGER')),'LEDGER'),verified=after.find(x=>norm(x.name)===norm(pending.item.name));if(!verified)throw Error('Master post-write verification failed');pending.item.tallyGuid=verified.guid;pending.item.masterOriginalName=pending.item.name;pending.item.masterFingerprint=pending.kind==='group'?groupFp(verified):ledgerFp(verified);pending.item.masterSyncStatus='synced';await put(state,pw,`MASTER_ACTION_APPLIED: ${pending.kind} ${action} ${pending.item.name}`);return}
const tallyMatchFor=a=>tallyLedgers.find(t=>(a.tallyGuid&&t.guid&&t.guid===a.tallyGuid)||norm(t.name)===norm(a.masterOriginalName||a.name));
const recoveredMissing=accounts.find(a=>a.masterMissingCycles&&tallyMatchFor(a));if(recoveredMissing){delete recoveredMissing.masterMissingCycles;delete recoveredMissing.masterTallyMissing;recoveredMissing.masterSyncStatus='synced';await put(state,pw,`MASTER_DELETE_CHECK_CLEARED: ledger ${recoveredMissing.name} found again in Tally`);return}
const linkedCount=accounts.filter(a=>a.masterFingerprint||a.tallyGuid||a.tallyMasterId).length;if(tallyLedgers.length<Math.max(1,Math.floor(linkedCount*0.75)))throw Error(`Master deletion safeguard: incomplete Tally ledger export (${tallyLedgers.length}/${linkedCount})`);
const missingLinked=accounts.find(a=>!a.masterDeletePending&&a.masterSyncStatus!=='pending'&&(a.masterFingerprint||a.tallyGuid||a.tallyMasterId)&&!tallyMatchFor(a));if(missingLinked){const used=state.vault.transactions?.some(t=>!t.deleted&&t.entries?.some(e=>e.accountId===missingLinked.id));missingLinked.masterMissingCycles=Number(missingLinked.masterMissingCycles||0)+1;missingLinked.masterTallyMissing=true;if(missingLinked.masterMissingCycles<2){await put(state,pw,`MASTER_DELETE_CHECK_1_OF_2: ledger ${missingLinked.name} missing from Tally`);return}if(used){missingLinked.active=false;missingLinked.masterSyncStatus='synced';delete missingLinked.masterMissingCycles;await put(state,pw,`MASTER_ACTION_APPLIED: Tally-deleted ledger retained inactive because vouchers use it: ${missingLinked.name}`);return}state.vault.accounts=accounts.filter(a=>a!==missingLinked);await put(state,pw,`MASTER_ACTION_APPLIED: Tally-deleted unused ledger removed from App: ${missingLinked.name}`);return}
const knownLedgerGuids=new Set(accounts.map(a=>norm(a.tallyGuid)).filter(Boolean)),knownLedgerMasterIds=new Set(accounts.map(a=>Number(a.tallyMasterId||0)).filter(Boolean)),appLedgerNames=new Set(accounts.map(a=>norm(a.name))),tallyOnly=tallyLedgers.find(t=>!appLedgerNames.has(norm(t.name))&&(!norm(t.guid)||!knownLedgerGuids.has(norm(t.guid)))&&(!Number(t.masterId||0)||!knownLedgerMasterIds.has(Number(t.masterId||0))));if(tallyOnly){accounts.push({id:Math.max(0,...accounts.map(a=>Number(a.id)||0))+1,name:tallyOnly.name,parent:tallyOnly.parent,category:nature(tallyOnly.parent),currency:tallyOnly.currency||state.vault.currency,openingBalance:tallyOnly.openingBalance,active:true,tallyGuid:tallyOnly.guid||undefined,tallyMasterId:tallyOnly.masterId||undefined,masterOriginalName:tallyOnly.name,masterFingerprint:ledgerFp(tallyOnly),masterSyncStatus:'synced'});await put(state,pw,`MASTER_ACTION_APPLIED: Tally ledger imported ${tallyOnly.name}`);return}
const tallyChanged=accounts.map(a=>({a,t:tallyLedgers.find(t=>(a.tallyGuid&&t.guid&&norm(t.guid)===norm(a.tallyGuid))||(a.tallyMasterId&&Number(t.masterId)===Number(a.tallyMasterId)))})).find(x=>x.t&&x.a.masterSyncStatus!=='pending'&&(x.a.masterFingerprint!==ledgerFp(x.t)||norm(x.a.name)!==norm(x.t.name)||norm(x.a.parent)!==norm(x.t.parent)));if(tallyChanged){Object.assign(tallyChanged.a,{name:tallyChanged.t.name,parent:tallyChanged.t.parent,category:nature(tallyChanged.t.parent),openingBalance:tallyChanged.t.openingBalance,currency:tallyChanged.t.currency||tallyChanged.a.currency,masterOriginalName:tallyChanged.t.name,masterFingerprint:ledgerFp(tallyChanged.t),masterSyncStatus:'synced'});await put(state,pw,`MASTER_ACTION_APPLIED: Tally ledger updated ${tallyChanged.t.name}`);return}
const ledgerBalances=parseLedgerBalances(await post(ledgerBalanceXml()));state.vault.tallyLedgerSnapshot={asOf:new Date().toISOString(),balances:ledgerBalances};await put(state,pw,`MASTER_SYNC_CLEAN: ${tallyGroups.length} groups, ${tallyLedgers.length} ledgers | Ledger balance snapshot refreshed (${ledgerBalances.length} ledger(s))`)}catch(e){console.error('MASTER_SYNC_ERROR:',e.message);process.exitCode=1}})();
