import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
const source=process.argv[2]; if(!source) throw new Error("Usage: node scripts/analyze-tally.mjs <tally-export-folder>");
const masterPath=path.join(source,"Master.xml"), dayPath=path.join(source,"DayBook.xml");
for(const p of [masterPath,dayPath]) if(!fs.existsSync(p)) throw new Error(`Missing ${p}`);
const decode=s=>s.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").trim();
const tag=(body,name)=>{const m=body.match(new RegExp(`<${name}>([\\s\\S]*?)<\\/${name}>`,`i`));return m?decode(m[1]):""};
const category=(name,parent)=>{const x=`${name} ${parent}`.toLowerCase();if(/bank|checking|saving|credit union/.test(x))return"Bank";if(/cash/.test(x))return"Cash";if(/investment|stock|share|mutual|broker|401|ira|equity/.test(x))return"Investment";if(/income|salary|interest received|dividend/.test(x))return"Income";if(/expense|expenditure|purchase|rent|utilities|insurance|medical|travel/.test(x))return"Expense";if(/loan|credit card|liabilit/.test(x))return"Liability";if(/asset|deposit|receivable/.test(x))return"Asset";return"Review"};
const readXml=p=>{const b=fs.readFileSync(p);if(b[0]===0xff&&b[1]===0xfe)return b.subarray(2).toString("utf16le");if(b[0]===0xfe&&b[1]===0xff){const s=Buffer.from(b.subarray(2));s.swap16();return s.toString("utf16le")}if(b.length>4&&b[1]===0)return b.toString("utf16le");return b.toString("utf8").replace(/^\\uFEFF/,"")};
const masters=readXml(masterPath); const ledgers=[]; const ledgerRe=/<LEDGER(?:\s[^>]*)?>([\s\S]*?)<\/LEDGER>/gi; let m;
while((m=ledgerRe.exec(masters))){const body=m[1],name=tag(body,"NAME"),parent=tag(body,"PARENT"),opening=Number(tag(body,"OPENINGBALANCE").replace(/,/g,""))||0;if(name)ledgers.push({name,parent,category:category(name,parent),openingBalance:opening})}
const tally=readXml(dayPath); const voucherRe=/<VOUCHER(?:\s[^>]*)?>([\s\S]*?)<\/VOUCHER>/gi;const types={},dates=[],issues=[];let vouchers=0,entries=0,balanced=0;
while((m=voucherRe.exec(tally))){vouchers++;const body=m[1],type=tag(body,"VOUCHERTYPENAME")||"Unknown",date=tag(body,"DATE"),guid=tag(body,"GUID");types[type]=(types[type]||0)+1;if(/^\d{8}$/.test(date))dates.push(date);const amounts=[...body.matchAll(/<AMOUNT>([^<]+)<\/AMOUNT>/gi)].map(x=>Number(decode(x[1]).replace(/,/g,""))).filter(Number.isFinite);entries+=amounts.length;const sum=amounts.reduce((a,b)=>a+b,0);if(Math.abs(sum)<0.01)balanced++;else if(issues.length<50)issues.push({guid:guid||`voucher-${vouchers}`,date,type,difference:Number(sum.toFixed(2))})}
const categories=ledgers.reduce((a,l)=>(a[l.category]=(a[l.category]||0)+1,a),{});const report={generatedAt:new Date().toISOString(),source:{masterFile:path.basename(masterPath),dayBookFile:path.basename(dayPath),checksum:crypto.createHash("sha256").update(tally).digest("hex")},coverage:{firstDate:dates.sort()[0],lastDate:dates.at(-1)},accounts:{count:ledgers.length,categories},vouchers:{count:vouchers,types,ledgerEntries:entries,balanced,needsReview:vouchers-balanced},sampleIssues:issues};
const out=path.resolve(".local-data");fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,"migration-report.json"),JSON.stringify(report,null,2));fs.writeFileSync(path.join(out,"ledger-classification.csv"),"Name,Parent,Category,Opening Balance\n"+ledgers.map(l=>[l.name,l.parent,l.category,l.openingBalance].map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"));console.log(JSON.stringify(report,null,2));